### ISSUE TITLE
Deprecated: auto_detect_line_endings is deprecated

### ISSUE THREAD

**Issue by svenskanda** [dallgoot/yaml#12]
Its deprecated and now your package is not working with composer. 

commit 3c12e64

**Comment by svenskanda** [comment]
the same problem your other commits since 8months - your packagist package is not up to date

**Comment by ch-devhost** [comment]
Good i have required your dev-master, but is not a good solution - a new Release after v0.3.2 - it's a better solution. You do a great work - why the time of two Years for no new Release?

**Comment by dallgoot** [comment]
Hi all,
there's a new version being currently working on. It will handle this problem and others but will require PHP version 8 minimum.
It should be out this month : march 2023

**Comment by svenskanda** [comment]
Nice - thanks - so many years of JSON and now I think for all etc is YAML perfect.

**Comment by dallgoot** [comment]
Fixed in 0.9.0.1
