### ISSUE TITLE
Cannot read sequences

### ISSUE THREAD

**Issue by scorninpc** [dallgoot/yaml#16]
Hello

First, thank you for this nice and complete lib

But i'm figuring out a problem that i cannot understand to help solve

When we get [sequence](https://yaml.org/spec/1.2.2/#block-sequences) like

![image](https://github.com/dallgoot/yaml/assets/2607849/8cfac1e3-cfec-4db8-aeb9-004f7f64d8b6)

We got this trace: https://pastebin.com/6RDa7Ccq

# My main code is just

```php
$yaml = \Dallgoot\Yaml\Yaml::parseFile(APPLICATION_PATH . "/../plugins/AuthMe/config.yml", NULL, NULL);
print_r($yaml);
```

**Comment by dallgoot** [comment]
Hi :) i will look into it and come back to you.

**Comment by dallgoot** [comment]
Issue is fixed in version 0.9.1.2
Thank you for your report !
Please confirm to me that problem is resolved so i can close this issue or provide any other relevant information :)

**Comment by antonioturdo** [comment]
Hi @dallgoot could I ask you why you deleted version 0.9.0? I'm using PHP 8.1.0 and now I can only use a 3 year old version...

**Comment by scorninpc** [comment]
Hello @dallgoot! Thank you for your help

In fact the lists works now, but appear a new problem

This yml can be parsed

![image](https://github.com/dallgoot/yaml/assets/2607849/a33ec43d-d564-4275-8225-0b5bc9a5f703)

but this throw a error

![image](https://github.com/dallgoot/yaml/assets/2607849/3d3f00a4-3b56-419f-9f4a-dbe3e147724c)

Anything after the sequence throw a error. If its back to previous section, its ok

![image](https://github.com/dallgoot/yaml/assets/2607849/100e0305-12f5-4e37-92ab-04d2533a05a9)

**Comment by dallgoot** [comment]
Hi, last commit fixes this issue. Closing it for now but feel free to re-open an issue if you still experience it.
Thank you for the report
