### ISSUE TITLE
Parsing of a quoted string containing colon+space causes problems

### ISSUE THREAD

**Issue by delkano** [dallgoot/yaml#18]
I have a file containing a line like this:
`title: "D: presentation"`

The library loads and parses without error, but when I try to use the string, I get a `stdClass could not be converted to string` error.

Looking (print_r) into the object gives me something even weirder:
`stdClass Object ( [] => presentation")`
The object seems to have an anonymous attribute containing everything behind the colon, including the quote.

If, however, I remove the space after the colon and leave the quoted string as "D:presentation" there's no issue, everything works as expected.

**Comment by dallgoot** [comment]
this was fix in last commit and will be available in upcoming version.
Thanks for your report
