### ISSUE TITLE
Associative array documentation

### ISSUE THREAD

**Issue by sharkodlak** [dallgoot/yaml#6]
Hi, is there a way to obtain associative array other than json_decode(json_encode($yamlObject), true)?

**Comment by dallgoot** [comment]
Hi Sharkodlak,
yes but it depends obviously on your YAML content.
Keep in mind that in YAML there's no "associative array" syntax declaration, you can however use a sequence that is tagged as "omap"

See here : https://yaml.org/spec/1.2/spec.html#id2760395   the example 2.26

Don't hesitate to drop me a line if needed. :)

**Comment by dallgoot** [comment]
Maybe i've read too quickly : if you want to convert a yamlObject which have properties you can simply use a
`$myvar = (array) $yamlObject`

**Comment by dallgoot** [comment]
@sharkodlak since there's no issue with dallgoot/yaml i'm closing this thread, feel free to re-open an issue if you have a question
